### ISSUE TITLE
django tinymce not loading on non-admin pages

### ISSUE THREAD

**Issue by hamzagh1998** [jazzband/django-tinymce#263]
I installed django-tinymce and add it to the INSTALLED_APPS and in the urls.py in my project folder
and i use HTMLField() in my app model
`from django.db import models
from tinymce.models import HTMLField

class MyModel(models.Model):
    body = HTMLField()`

and I create the form and views
`from .models import MyModel
from django import forms

class MyForm(forms.ModelForm):
    class Meta:
        model = MyModel
        fields = ['body',]`

`from django.shortcuts import render
from .form import MyForm

def index(request):
    return render(request, 'app/index.html', {'form':MyForm()})`
the template
`<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form method="post">
      {% csrf_token %}
      {{ form }}
    </form>
  </body>
</html>
`
the tinymce loading in the admin page but not in the template form!

**Comment by Natim** [comment]
Did you register the form media?

https://docs.djangoproject.com/en/3.0/topics/forms/media/

**Comment by Zswdhy** [comment]
django-tinymce   没有起到富文本的作用 是怎么回事  每次加载js文件的时候 总是找不到，

**Comment by Natim** [comment]
@Zswdhy which version are you using? What is your config?

**Comment by lj2tj** [comment]
> @Zswdhy which version are you using? What is your config?

Im using
Django         3.0.7
django-tinymce 3.0.2

my setting is:
TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table,spellchecker,paste,searchreplace",
    'theme': "silver",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'width':800,
    'height':600,
}
and also i tried:
TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table,spellchecker,paste,searchreplace",
    'theme': "advanced",
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'width':800,
    'height':600,
}
My nginx config:
        location /static/django_tinymce {
            alias /usr/share/nginx/html/SupplyChainTestPlatform/static/django_ti
nymce;
        }

        location /tinymce {
            alias /usr/share/nginx/html/SupplyChainTestPlatform/static/tinymce;
        }

I faced the issue that could not load "http://my address/static/tinymce/themes/advanced/theme.min.js"

Would you take a look this issue? Thanks a lot.

**Comment by lj2tj** [comment]
btw, there are only 2 thems in the themes dolder: mobile, silver. Anyother infomation if you need, please let me know. thank you very much.

**Comment by lj2tj** [comment]
btw, there are only 2 themes in the themes folder: mobile, silver. Anyother infomation if you need, please let me know. thank you very much.

**Comment by lj2tj** [comment]
Sorry, please ignore my question. After restarting my nginx service and uwsgi service several times it works. And maybe reload nginx conf helps me.
