### ISSUE TITLE
$ and jQuery are undefined after loading django-tinymce media

### ISSUE THREAD

**Issue by jammon** [jazzband/django-tinymce#265]
After loading django-tinymce media $ and jQuery are undefined:
```html
<script>
  console.log(typeof($))
  console.log(typeof(jQuery))
</script>
{{ form.media }}
<script>
  console.log(typeof($))
  console.log(typeof(jQuery))
</script>
```
The output is:
```
function
function
undefined
undefined
```

I have no idea where to start looking for the problem. I found this error after upgrading from 2.8.0 to 3.0.2 via `pip install -U django-tinymce`.
Thank you for any help!

**Comment by jammon** [comment]
I have `TINYMCE_INCLUDE_JQUERY = False` in the settings.

**Comment by Natim** [comment]
@urtzai is this something you can investigate?

**Comment by lguariento** [comment]
Hello, I have the same issue. Is it not possible to use an updated version of Jquery (your own) and leave the `TINYMCE_INCLUDE_JQUERY = False` false in the settings? I have to load two versions of jQuery as it is. Thanks :)

**Comment by mgZenMaster** [comment]
This took me hours to figure out. Please fix this.
In the init_tinymce.js right at the top, it checks if the variable `django` is undefined, and if it is, calls `jQuery.noconflict(true)` which unsets $ (to avoid conflicts with other frameworks) and also `jQuery` for some reason.
There is a workaround, just define `django` with something, e.g.
```
<script type="text/javascript">'
       var django = 'dummy';
</script>
```
That way the script won't call `jQuery.noconflict(true)`, but there should be a better way to do this, e.g. make it a setting if `jQuery.noconflict(true)` should be called at all.

**Comment by claudep** [comment]
jQuery was removed from django-tinymce in d168d1501e7c2fa1cecf27351a4e1f9553095113, so this issue should be obsolete.
