### ISSUE TITLE
Combining TinyMCE field with autocomplete in admin breaks autocomplete fields

### ISSUE THREAD

**Issue by ahecht** [jazzband/django-tinymce#282]
It seems that using django-tinymce on an admin form field in a class that also uses the ModelAdmin's `autocomplete_fields` option causes a JavaScript error that causes the autocomplete fields to break. This only happens if the TinyMCE field is positioned _after_ the autocomplete fields. It happens using HTMLField() or a widget.

The javascript error comes from autocomplete.js:
```javascript
TypeError: $element.select2 is not a function. (In '$element.select2(settings)', '$element.select2' is undefined)
```

The issue is reproducible with a super basic app, (I just followed [Django's "my first app" tutorial](https://docs.djangoproject.com/en/3.0/intro/tutorial01/)), and adding only django-tinymce.

---

**models.py**
```python
from django.db import models
from tinymce.models import HTMLField


class Question(models.Model):
    question_text = models.CharField(max_length=200)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    description = HTMLField()

```

**admin.py**
```python
from django.contrib import admin
from django.forms.models import ModelForm

from .models import Question, Choice

class QuestionAdmin(admin.ModelAdmin):
    search_fields = ['question_text']

class ChoiceAdmin(admin.ModelAdmin):
    autocomplete_fields = ['question']
    fields = ('question', 'description', )

admin.site.register(Question, QuestionAdmin)
admin.site.register(Choice, ChoiceAdmin)
```

In this state, the javascript error is thrown and the Question field is rendered as an unusable select element with no options.

If the `description` field is moved before the `question` field, the autocomplete works as expected.
```
fields = ('description', 'question', )
```

**Comment by silviomoreto** [comment]
I am having the same issue using `forms` widget...

**Comment by claudep** [comment]
I made some tests and it looks like removing jQuery dependency (d168d1501e7c2fa1cecf27351a4e1f9553095113) had the nice side-effect to fix this issue.

**Comment by silviomoreto** [comment]
@claudep are you planning to create a new version release? So I can install the version, instead of the branch/commit

**Comment by Natim** [comment]
@silviomoreto that's indeed something that we can do.
