### ISSUE TITLE
Language fr doesn't load

### ISSUE THREAD

**Issue by claudep** [jazzband/django-tinymce#285]
In commit 4ade40f, the language files were updated and `fr.js` was replaced by `fr_FR.js`. Now my instance is still trying to reach `fr.js` and fails. Is this a bug or a configuration issue?

**Comment by andre-silva-14** [comment]
I have the same issue.
I see two problems here:

1. The language file name is, as I understand it, currently being retrieved/built from the `LANGUAGE_CODE` setting or more specifically from `django.utils.translation.get_language()`, and then being parsed by `widgets.py` line 126 (`language = language[:2] if language is not None else "en"`).
_**This does not work anymore to the new file structure, and generates a bug.** I.e. `fr_FR.js`, `pt_PT.js` cannot be used._

2. The above wouldn't be a significant issue if it would be possible to override the language configuration, but it's not. It works the other way arround, HTML `lang` has priority over `language` on `TINYMCE_DEFAULT_CONFIG`, and I can understand why is that so. Unless you change the HTML, or there's some other configuration that I'm not aware of, it is pretty much impossible to override the `language` setting.

As a temporary **workarround** on this issue I've built a custom function:
```python
def parse_language(lang: str) -> str:
    try:
        language, dialect = lang.split('-')
        return f"{language}_{dialect.upper()}"
    except ValueError:
        return lang
```
And, edited `widgets.py` line 126 accordingly:
```python
language = parse_language(language) if language is not None else "en"
```

All languages are now being loaded normally.

**Comment by andre-silva-14** [comment]
Since the `language` property on `TINYMCE_DEFAULT_CONFIG` was never being used and was always being overwritten by Django's `LANGUAGE_CODE`, I've also updated the `get_language_config()` to take into consideration `TINYMCE_DEFAULT_CONFIG.language` with a higher priority than `LANGUAGE_CODE`.
This way, if an user is not satisfied with the automatic language selection from Django's Settings, he can always update the `language` property on `TINYMCE_DEFAULT_CONFIG` to change language configurations, which was not possible before.

I'll send a pull request of this update later.

**Comment by claudep** [comment]
The issue was also reported in TinyMCE (https://github.com/tinymce/tinymce/issues/5429). The problem is that language codes are inconsistent, sometimes the `<lang>.js` is used, sometimes the `<lang>_<country>.js`. This is a known issue with the Transifex platform where translators can choose either version of the language. If the package maintainer isn't attentive, it leads to such situations.

I'm currently working on a workaround for django-tinymce.

**Comment by c4ntin** [comment]
The bug still present or evolve... If you define the language option with "fr_FR" ou "fr", tinymce try to retrieve "https://cdn.tiny.cloud/1/xxxxxxxx/tinymce/5.6.2-104/langs/fr.js" that doesn't exist but only the file fr_FR.js exist.
