### ISSUE TITLE
Update documentation regarding preview

### ISSUE THREAD

**Issue by lorenzomorandini** [jazzband/django-tinymce#314]
Hi,
the documentation contains a section explaining how to enable to preview plugin using the "plugin_preview_pageurl" config parameter. From what I can see that parameter has been removed and the plugin can now be enabled using
```
'plugins': 'preview',
'toolbar': 'preview'  # only required if you want to add the button to the toolbar
```

Should the documentation be updated?

**Comment by Natim** [comment]
Yes please. Could you file a pull-request? Thanks !

**Comment by lorenzomorandini** [comment]
Looking at docs/usage.rst it seems that the documentation has already been updated, so maybe the version on readthedocs.io isn't the last one?

**Comment by Natim** [comment]
@jannisleidel can you help me reactivating the webhook? I don't have the permissions to do so. https://readthedocs.org/dashboard/django-tinymce/integrations/

**Comment by claudep** [comment]
@Natim just fixed the readthedocs build.

**Comment by jezdez** [comment]
Ah, please remember to use either @jazzband/roadies or @jezdez to ping me, not my alter-ego @jannisleidel. Than you!
