### ISSUE TITLE
Error with bootstrap_modal_forms in Django

### ISSUE THREAD

**Issue by sarkkk** [jazzband/django-tinymce#317]
In a bootstrap modal form is not submitting and each time I tried to submit it fire an error saying that (specific) field is required.

**Comment by claudep** [comment]
I don't see why django-tinymce is at fault here. If you can demonstrate that django-tinymce is doing something wrong, then please reopen with more details (maybe with a sample project?).

**Comment by BoPeng** [comment]
I am experiencing the same issue. I think the problem is somehow with tinymce does not "bind" to the modal field, so empty value is passed to the backend.
