### ISSUE TITLE
Failed to load language en_US

### ISSUE THREAD

**Issue by pembo13** [jazzband/django-tinymce#318]
JavaScript Error: Failed to load language: en_US

According to https://github.com/tinymce/tinymce/issues/4228 language when expecting English causes an error, I don't see how to get past this without editing the code generating the config data.

**Comment by claudep** [comment]
Would be great if you could test the suggested fix in your use case.

**Comment by pembo13** [comment]
I ended up monkey patching to get things to work for now.

    from tinymce.widgets import TinyMCE

    def get_mce_config(self, attrs):
        config = self._get_mce_config(attrs)

        if config.get('language', '').lower() == 'en_us':
            config.pop('language')

        return config

    TinyMCE._get_mce_config = TinyMCE.get_mce_config
    TinyMCE.get_mce_config = get_mce_config

**Comment by mrts** [comment]
Will there be a release with this fix soon?
