### ISSUE TITLE
Having struggle with docs and could not find enough info on image upload

### ISSUE THREAD

**Issue by eemektas** [jazzband/django-tinymce#325]
Thanks for you to made this project first. Beside of it's efficiency and benefits of TinyMCE, it's so hard to implement to a project even with deep dived searches. The docs on https://django-tinymce.readthedocs.io/en/latest/ seems changed at 2009 lastly. I think it would be handy to hear some of the latest changes and implementation methods. Would be pleasured to have them or some helps. Have a good one.

**Comment by claudep** [comment]
The build is currently failing on readthedocs, I'll see if I can get help about fixing this.

**Comment by Natim** [comment]
> ConfigError: There is a syntax error in your configuration file: invalid syntax (conf.py, line 37)

**Comment by Natim** [comment]
I guess it is the f-string usage while the build was using python2.7. I switch it to Python 3. It should be fixed.
