### ISSUE TITLE
TINYMCE_FILEBROWSER does not have effect on filebrowser integration

### ISSUE THREAD

**Issue by Krzy65siek** [jazzband/django-tinymce#326]
Version: 3.1.0 installed with pip, Django 3.1.

It looks like a simple mistake - setting TINYMCE_FILEBROWSER variable in settings.py defines 'file_browser_callback'. This had changed in recent TinyMCE versions as it needs to define 'file_picker_callback', so TINYMCE_FILEBROWSER has no effect.

Even if you set TINYMCE_FILEBROWSER=True, image select icon does not show in tinyMCE.

**Comment by Natim** [comment]
Hello @Krzy65sie,

Thank you for taking the time for your feedback.

Would you be able to create a PR with the fix you are suggesting?

**Comment by claudep** [comment]
I think this will be fixed in the next version by 51483344802.

@Natim, maybe time for a release?

**Comment by Natim** [comment]
Yes let's do that !
