### ISSUE TITLE
Getting 404 error as Tinymce tries to load en_US language pack by default

### ISSUE THREAD

**Issue by edumats** [jazzband/django-tinymce#334]
When setting django-tinymce on my project, I noticed on my browser's console that it tries to get a en_US.js file and this results in a 404 error, as the file does not exist in the lang folder. I didn't set a language for specifically for it, but in the django-tinymce documentation it says that I would need a language pack for every language set up in `settings.LANGUAGES`.

As en_US is the default language for a Django project and that's what's set for my settings.LANGUAGES, I find it strange that it tries to get a language pack for it. And there is no en_US languages packs available on the official tinymce [website](https://www.tiny.cloud/get-tiny/language-packages/)

Am I missing something? The tinymce widget works perfectly, but the error really annoys me.

**Comment by claudep** [comment]
This is supposed to be fixed in 3.2.0. Do you run that version?

**Comment by claudep** [comment]
Without response, closing.
