### ISSUE TITLE
TinyMCE Cloud CDN needs referrerpolicy="origin" in script tag

### ISSUE THREAD

**Issue by jboolean** [jazzband/django-tinymce#335]
To avoid checking third party code into VCS, I'd like to load TinyMCE from a CDN and the CDN provided by TinyMCE is TinyMCE Cloud.  TinyMCE Cloud [requires](https://www.tiny.cloud/docs/cloud-deployment-guide/editor-and-features/) that the script tag have a `referrerpolicy` of `origin` set as they require the origin to match against a whitelist of domains you configure.

This plugin inserts a script tag into the Django admin template, but without the `referrerpolicy` option, so it fails with "invalid origin". Is there a way to fix this?

**Comment by claudep** [comment]
FWIW, no need to include TinyMCE into VCS, django-tinymce includes all TinyMCE code by default.

**Comment by jboolean** [comment]
Whoops. I confused myself. Thanks!
