### ISSUE TITLE
AttributeError: 'ellipsis' object has no attribute 'startswith' when using django_tinymce

### ISSUE THREAD

**Issue by millerthegorilla** [jazzband/django-tinymce#339]
fyi,  when copying and pasting the settings from the readthedocs page, I get the above uninformative message, that results from the inclusion of a comment in the settings dictionary.  Had me tearing my hair out for a few minutes.

TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",
    "width": "960px",
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "
    "fullscreen insertdatetime media table paste code help wordcount spellchecker",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
    "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "language": "es_ES",  # To force a specific language instead of the Django current language.   ***REMOVE THIS COMMENT FROM DOCS PLEASE***
}

**Comment by claudep** [comment]
There is no ellipsis in this comment, I guess your problem comes from the ellipsis in the `TINYMCE_EXTRA_MEDIA` setting. You are supposed to edit and replace the ellipsis with real content, if any.
