### ISSUE TITLE
CodeSample plugin removes single linebreak

### ISSUE THREAD

**Issue by omidshojaee** [jazzband/django-tinymce#341]
**django-tinymce v3.2.0**

In the editor I input the Python code and it works fine as below:

```
from django.contrib.auth import get_user_model
list(get_user_model().objects.filter(is_superuser=True).values_list('username', flat=True))
```
Here I press the Enter key one time at the end of first line.

However, when I see the output on the HTML page it looks like this:

```
from django.contrib.auth import get_user_modellist(get_user_model().objects.filter(is_superuser=True).values_list('username', flat=True))
```
The two lines are concatenated.

Now if I go back to editor and press the Enter key one more time at the end of first line:

```
from django.contrib.auth import get_user_model

list(get_user_model().objects.filter(is_superuser=True).values_list('username', flat=True))
```
The HTML output is like this:

```
from django.contrib.auth import get_user_model

list(get_user_model().objects.filter(is_superuser=True).values_list('username', flat=True))
```
So this time the lines are not concatenated, but there's an extra empty line.
So one Enter key doesn't work, two Enter keys work correctly.

I've tested on both Microsoft Edge and Firefox.

**Comment by some1ataplace** [comment]
You need to have something like this inside of your TINYMCE_DEFAULT_CONFIG setting:

```
    'force_p_newlines': True,
    'force_br_newlines' : False,
    'forced_root_block' : True,
```

You may need to play around with these settings to get your desired result.
