### ISSUE TITLE
Not working on dynamically added inline forms

### ISSUE THREAD

**Issue by lostpoint-ru** [jazzband/django-tinymce#348]
Django==3.1.5
django-tinymce==3.2.0

HTMLField is used in a nested class, django admin is configured to display nested class as TabularInline. 
When parent class admin page is loaded, all existing inline forms are correctly transformed to TinyMCE editor fields, but when I click on "add new %childclass%", a new inline form instance is created with a regular TextField instead of TinyMCE.

![tinymce-inline](https://user-images.githubusercontent.com/67120046/112230713-667d0200-8c46-11eb-81a5-314f0c22b7a2.jpg)

**Comment by claudep** [comment]
Would you be able to test with django-tinymce master? Otherwise, having a sample project which reproduces the error would be great.

**Comment by lostpoint-ru** [comment]
Thanks for reply.

Just tried django-tinymce master manually cloned from github and it seems to work properly.

Is there some recent relevant fixes waiting to be merged into release?

**Comment by Natim** [comment]
I just released 3.3.0 so that you can have the fix for this issue.

**Comment by lostpoint-ru** [comment]
Thanks :)

**Comment by vvalentinvolkov** [comment]
I have the same issue on django = 4.1 and django-tinymce = 3.6.1.

Every first added `inline` has a regular TextField. I can save object than added before `inlines` work good but if i add another one i get regular TextField again. Every next added `inline` are good.

So problem is only in the first added but not saved `inline`.

**Comment by claudep** [comment]
@vvalentinvolkov It's worth nothing commenting on closed issues. Please create a new issue and provide a small sample project which can be used to demonstrate the problem.
