### ISSUE TITLE
Wheel dist includes the tests package

### ISSUE THREAD

**Issue by ionelmc** [jazzband/django-tinymce#355]
This breaks my application's tests since the tests package in site-package will take precedence.

This regression appeared in 3.3 (3.2 is fine). Looks like the cause is this change: https://github.com/jazzband/django-tinymce/commit/9175803df0b41b8d6d8e84b80bdc1da404dec1ed#diff-41d5a52589e0480be9c099d2bba7a8135b8b0d71bcbb8df3582a8df1c2295003

Looks like the intended change there was to include the test in the sdist. A change to `find_packages` to use `exclude` or `include` is also needed.

Similar problem to https://github.com/3YOURMIND/django-migration-linter/issues/147

**Comment by hsmett** [comment]
Hello,
Just a quick note to let you know that this issue is still there.
The 'tests' directory packaged with the application is installed in 'site-packages/tests'.
Thank you

**Comment by claudep** [comment]
Patch welcome :-)
