### ISSUE TITLE
Editor toolbar overlaps calendar on DateField in admin

### ISSUE THREAD

**Issue by stac47** [jazzband/django-tinymce#358]
Hello,
I have a model that is managed in admin side of my site:
```python
class Race:
...
    date = models.DateField(verbose_name=_("date"))
    club = models.ForeignKey(Club,
                             on_delete=models.PROTECT,
                             null=True,
                             verbose_name=_("club"))
    description = tinymce_models.HTMLField(blank=True,
                                           default="",
                                           verbose_name=_("description"))
```
Everything works well except the display when I click on the calendar to select a date (see picture).
<img width="931" alt="tinymce_display_bug" src="https://user-images.githubusercontent.com/3864333/122031795-5309af00-cdcf-11eb-81a9-bd28207421b1.png">
I am currently using django-tinymce version 3.3.0 with django 3.2.4 and I don't set anything on regarding tinymce in the settings.py.
I have the same result within Firefox and Safari.
Thanks in advance for your help,

**Comment by zealousKestrel** [comment]
why don't you put datetime order to the last index ?

**Comment by zealousKestrel** [comment]
btw in your tinymce have a image upload ?

**Comment by jcanning** [comment]
I have the same issue. I find it odd that the only solution is to move the date field below. Did anyone come up with something better than this?

I am using Django 4.0 and Django-TinyMCE 3.4 and can confirm this issue still exists.

**Comment by claudep** [comment]
This is a z-index CSS issue. While tinymce has `.tox .tox-editor-header { z-index:1; }` to force the editor header to the foreground, Django's calendar widget doesn't touch the `z-index` property of calendar items. A workaround would be to change that z-index in your own css, either for tinymce `.tox-editor-header` or for Django's `calendarbox`. I'm not yet sure about a proper resolution of this issue.

**Comment by stac47** [comment]
Thanks all for you answers. Indeed, I tweaked my CSS to solve this. I raised that ticket to help maintainers improving this great component: as a user, I would expect tinymce would be perfectly integrated with the default Django admin components. Sorry I cannot help more: my knowledge in UI technologies is very low.
