### ISSUE TITLE
init_tinymce.js not found in django admin panel

### ISSUE THREAD

**Issue by devanghingu** [jazzband/django-tinymce#360]
I configured exactly mentioned in  **README.rst**  it's working fine in local as well in development server. but when in pushed into staging. it's not working. 
therefore i started debugging and found that `static/django_tinymce/init_tinymce.js` url has 404.

**Comment by claudep** [comment]
Most probably a static file deployment issue. Reopen if you can show that django-tinymce does something wrong.
