### ISSUE TITLE
Add language to codesample plugin

### ISSUE THREAD

**Issue by omidshojaee** [jazzband/django-tinymce#365]
Currently my ```codesample``` plugin has these languages: HTML/XML, JavaScript, CSS, PHP, Ruby, Python, Java, C, C# and C++.

How to edit this in ```settings.py```? I want to add ```django``` to that list.

**Comment by some1ataplace** [comment]
Add this to your TINYMCE_DEFAULT_CONFIG setting:

```
    'codesample_languages': [
        {'text': 'Django', 'value': 'python'},
    ],
```

Plugin javascript file:

https://github.com/jazzband/django-tinymce/blob/master/tinymce/static/tinymce/plugins/codesample/plugin.min.js

You will find this code snippet in that javascript file:

```
            n = s.getParam("codesample_languages") || [
                { text: "HTML/XML", value: "markup" },
                { text: "JavaScript", value: "javascript" },
                { text: "CSS", value: "css" },
                { text: "PHP", value: "php" },
                { text: "Ruby", value: "ruby" },
                { text: "Python", value: "python" },
                { text: "Java", value: "java" },
                { text: "C", value: "c" },
                { text: "C#", value: "csharp" },
                { text: "C++", value: "cpp" },
            ],
```
Use https://unminify.com/ to make the minified file easier to read.

Related Issue and possibly another method to add more languages:

https://github.com/jazzband/django-tinymce/issues/217
