### ISSUE TITLE
How can I use it with StructBlock

### ISSUE THREAD

**Issue by hatimmakki** [jazzband/django-tinymce#395]
Hey, 
I am using this package with a wagtail Django project.
The text following field shows normally:

```python
class FindPage(Page):
    banner_title = HTMLField(blank=True)

```

but the following, doesn't:

```python
class DirectoryListBlock(blocks.StructBlock):
    title = HTMLField(required=False)
```

how can I use HTMLField with StructBlock ?

**Comment by claudep** [comment]
Shouldn't this be asked to Wagtail devs first?
