### ISSUE TITLE
Can't import module tinymce

### ISSUE THREAD

**Issue by bobort** [jazzband/django-tinymce#400]
I used pipenv to install.

`pipenv install django-tinymce`

When importing `HTMLField`,I get an error:

`from tinymce.models import HTMLField`

`ModuleNotFoundError: No module named 'tinymce.models'`

I investigated the site-packages directory for my virtual environment. There is no models.py file in the directory.
Several other files appear to be missing.

Please update the package accordingly.

**Comment by claudep** [comment]
I guess that if it were an issue on django-tinymce side, many people would have complained recently. So I can only suggest you debug or find support for this issue on your system. Reopen if you can more precisely point to an issue in django-tinymce.
