### ISSUE TITLE
Is there a current version on Pypi?

### ISSUE THREAD

**Issue by maksam07** [jazzband/django-tinymce#402]
Hello! I see that the latest version on the pypi is from Nov 25, 2021. But also, a lot of commits have already been made in this repository. Do I get the latest version from pypi?

**Comment by Natim** [comment]
I guess if you need support for the latest Django version we should probably make a release yes.

**Comment by maksam07** [comment]
Now I am developing a project on django 4.1 version. It would be great to have full support and the latest project updates

**Comment by claudep** [comment]
3.5.0 was released today.
