### ISSUE TITLE
How to hyperlink html id?

### ISSUE THREAD

**Issue by mszahan** [jazzband/django-tinymce#406]
The hyperlink plugins only allow linking the URL. But I need to hyperlink a HTML id for taking the user to that section on click?

**Comment by claudep** [comment]
Sorry, but I think this is more a TinyMCE support question rather than a django-tinymce issue, right?

**Comment by merwok** [comment]
(the answer is that you want links like `#id` instead of `/same/site/link` or `https://domain/path`)
