### ISSUE TITLE
Language not shipped from Transifex

### ISSUE THREAD

**Issue by JeanGauthier** [jazzband/django-tinymce#407]
Hello,
I noticed that the Occitan language, oc, is not present on this git.
Is this a synchronisation issue?

Best regard

**Comment by claudep** [comment]
I guess that at the moment we last synced TinyMCE (5.10.1), Occitan did not exist.

**Comment by claudep** [comment]
Go to https://www.tiny.cloud/get-tiny/language-packages/, click on "TinyMCE 5 all languages" at the bottom of the page, and you'll see there's no Occitan in it.

**Comment by JeanGauthier** [comment]
Hello thanks for the information.
What to do then?

**Comment by claudep** [comment]
If you are in a hurry, you can get the Occitan translation file from the TinyMCE website and put it in your langs directory yourself.

On the longer term, Occitan will be included in this package when we upgrade to TinyMCE 6. For that, someone will have to check the compatibility issue it presents for current django-tinymce users.
