### ISSUE TITLE
Is the selector config required but not stated in the docs?

### ISSUE THREAD

**Issue by Nengha-John** [jazzband/django-tinymce#421]
I have just spent a few hours debugging why my form field did not display any rich text feature in my frontend. I tried several solutions including setting `TINYMCE_JS_URL`,`TINYMCE_JS_ROOT` to both CDN values and relative paths but did not work till I used the sample code on [the website](https://www.tiny.cloud/get-tiny/) after viewing [this](https://stackoverflow.com/a/27193326/19026115) stackoverflow answer which suggested defining a selector for the target elements.

Config that actually works:
`TINYMCE_DEFAULT_CONFIG = {
".....",
"selector": "textarea",
"......"
}`

After setting up the `selector` config in `TINYMCE_DEFAULT_CONFIG`, the rich text features are displayed but [the docs](https://django-tinymce.readthedocs.io/en/latest/usage.html) do not state that. Is that a short coming in the documentations?

**Comment by some1ataplace** [comment]
It is possible that the lack of information on the selector configuration option in the Django TinyMCE documentation is a shortcoming. The selector option is used to specify the CSS selector for the element(s) that you want to apply the TinyMCE editor to.

Without this configuration, the TinyMCE editor may not be applied to the correct element, which could result in the behavior you experienced where the rich text features were not displayed.
