### ISSUE TITLE
Support for Django 4.2

### ISSUE THREAD

**Issue by blokkies48** [jazzband/django-tinymce#448]
Will there be support for django 4.2 and greater? If so when will it be released?

**Comment by blokkies48** [comment]
I got this error

site-packages/tinymce/widgets.py", line 17, in <module>
    from django.utils.encoding import smart_text
ImportError: cannot import name 'smart_text' from 'django.utils.encoding' 

Then I check the package on pypi and it is showing only support up to Django 4.1 and python 3.10, where I am using Django 4.2 and python 3.11. So I was just curious. If it should be able to run Django 4.2 then the issue is probably on my side.

**Comment by claudep** [comment]
This error shows that you are using an outdated version of django-tinymce. Use the latest released version (3.6.1) and it should run fine on Django 4.2.
