### ISSUE TITLE
Release 3.7.0 misses files

### ISSUE THREAD

**Issue by claudep** [jazzband/django-tinymce#454]
With the migration to PEP508 compatible build (pyproject.toml), it looks like many files are missing in the release. I suspect we should re-introduce a MANIFEST file.

**Comment by claudep** [comment]
Also note that I have not the necessary permissions to remove the release on PyPi.

**Comment by merwok** [comment]
This was the correct step. pyproject.toml does not replace setuptools files fully, nor is setuptools legacy. What changed is that pip (and other tools than can now exist) does not assume a project is using setuptools, and does not use a setup.py script as interface. So you need pyproject.toml to tell install tools how you build, and if you choose setuptools you still need to follow its docs and use its config files: metadata in setup.py and/or setup.cfg and/or pyproject.toml, file collection using MANIFEST.in or a VCS plugin, etc.
