### ISSUE TITLE
init_tinymce.js not coming over CDN

### ISSUE THREAD

**Issue by Natgho** [jazzband/django-tinymce#462]
I'm trying to configure tinymce's css and js files to come through the CDN, but no matter what I do, the "init_tinymce.js" file does not come through the CDN. Could it be a bug?

settings.py;
```python
TINYMCE_JS_URL = "https://cdnjs.cloudflare.com/ajax/libs/tinymce/7.0.0/tinymce.min.js"
TINYMCE_COMPRESSOR = False

TINYMCE_DEFAULT_CONFIG = {
    'theme': 'silver',  # Magic here
}
```
Proof;
![image](https://github.com/jazzband/django-tinymce/assets/6623948/2cb88873-372e-4815-b190-7f14df954feb)

**Comment by claudep** [comment]
`init_tinymce.js` is not a file from TinyMCE, it is specific to this package, so it cannot come from a CDN (unless your project static files are on a CDN).
