### ISSUE TITLE
Version 4.0.0 listed pypi but not on Github or documentation

### ISSUE THREAD

**Issue by khink** [jazzband/django-tinymce#466]
On pypi we see: https://pypi.org/project/django-tinymce/4.0.0/#history with a date of "Mar 27, 2024".

However, there's no Github release (https://github.com/jazzband/django-tinymce/releases) or documentation update (https://django-tinymce.readthedocs.io/en/latest/history.html).

What is changed in 4.0.0? Are there breaking changes?

**Comment by Natim** [comment]
The release is here: https://github.com/jazzband/django-tinymce/releases/tag/4.0.0
The changelog is here: https://raw.githubusercontent.com/jazzband/django-tinymce/master/CHANGELOG.rst

**Comment by khink** [comment]
Thank you!
