### ISSUE TITLE
Support for TinyMCE 7 and beyond

### ISSUE THREAD

**Issue by MrkGrgsn** [jazzband/django-tinymce#468]
We've just noticed that TinyMCE has taken the same approach as CKEditor and made version 7 available under GPLv2 or alternatively a commercial license  (https://github.com/tinymce/tinymce/issues/9453). I couldn't see any mention of this in issues here and was wondering whether you will aim to support TinyMCE 7 and subsequent releases?

**Comment by claudep** [comment]
We are not in a rush to support the most recent versions of TinyMCE, we just added TinyMCE 6 compatibility in django-tinymce 4.0. But yes, at some point this project will have no other choices than follow TinyMCE development and hence its license policy. As long as some devs are keen to contribute to this package, even in a GPL context, it will continue to support TinyMCE evolution.

**Comment by MrkGrgsn** [comment]
Thanks @claudep, that's reassuring. It will be interesting to see whether the change to GPL pushes clients and developers away to different libraries. 🤞 

Just noting here for reference that the EOL for open source v6 is 31 October 2024 ([1](https://github.com/tinymce/tinymce/discussions/9609)).

I see that the premium version of 6.8 is supported until 6 June 2025 ([2](https://www.tiny.cloud/docs/tinymce/latest/support/)) and the community edition of v5.10 received security updates for 7 months after premium support finished in April 2023 ([3](https://www.tiny.cloud/docs/tinymce/5/changelog/), [4](https://www.tiny.cloud/docs/tinymce/5/enterprise-system-requirements/)), so perhaps we can hope that open source 6.8 will keep receiving fixes until June 2025!

**Comment by philgyford** [comment]
It's quite confusing that the README, the front page of this repo, says that it uses TinyMCE 7.8.0, when the released version uses 6.8.4.

I realise why the discrepancy but, being a bit slow today, I did waste 20 minutes wondering why my installed version wasn't as up to date as I thought it should be.

**Comment by mardukbp** [comment]
It IS version 7.8.0: https://github.com/jazzband/django-tinymce/blob/master/tinymce/static/tinymce/tinymce.min.js

**Comment by alstr** [comment]
The license for the repo still says MIT which may be confusing and/or misleading for some.

As useful as this plugin has been I think the last v6 release is the jumping off point for me, as I can't agree to v7. If I want to use Tiny MCE I'll probably just use the free Tiny Cloud v8 version directly. I created a simple integration in my own Django project and while it has some limitations it worked fine for my situation.
