### ISSUE TITLE
The TinyMCE javascript code is not being loaded in the admin 

### ISSUE THREAD

**Issue by eduardo-boutiquenumerique** [jazzband/django-tinymce#469]
I'm using Django 3.2 and django-tinymce 4.0.0.

"tinymce" is included in the installed apps and I have added the line `path('tinymce/', include('tinymce.urls')),` to my urls.py file.

The only "non standard" thing I have is that I have created a subclass of admin.AdminSite. 

I don't know when this stopped working, but it was working on Django 1.11.29 (I know, quite old) with django-tinymce 2.6.0.

When I look at the html source code of an admin page supposed to have tinymce widgets, the class "tinymce" is present in the texarea but there is no call to the js. Checking in chrome dev tools -> network, I can confirm that no js is being requested.

What could be the issue here ?

**Comment by Pantzan** [comment]
In my setups, I've downloaded the tinymce source code and in Django settings I set the js file so django-tinymce can read it.
`TINYMCE_JS_URL = os.path.join(settings.STATIC_URL, "tinymce/tinymce.min.js")`

Another reason I can think of making the js files not loading is incorrect usage. Do you load the tinymce **widget** in `TextFields` and `CharFields`? 

```
body = TextField(
       required=False,
       widget=TinyMCE(),
   )
```

**Comment by JosephPaetz** [comment]
Experiencing the same issue.  Getting 200 responses for all the requested media files from within the admin:
June 02, 2024 - 13:24:46
Django version 5.0.6, using settings 'settings'
Starting ASGI/Daphne version 4.1.2 development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
HTTP GET /admin/web/testpage/add/ 200 [0.06, 127.0.0.1:50965]
HTTP GET /static/admin/css/base.css 200 [0.04, 127.0.0.1:50965]
HTTP GET /static/admin/css/dark_mode.css 200 [0.04, 127.0.0.1:50966]
HTTP GET /static/admin/css/nav_sidebar.css 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/css/forms.css 200 [0.00, 127.0.0.1:50966]
HTTP GET /static/admin/css/responsive.css 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/js/vendor/jquery/jquery.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/css/widgets.css 200 [0.00, 127.0.0.1:50965]
HTTP GET /tinymce/compressor/ 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/js/jquery.init.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/django_tinymce/init_tinymce.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/js/core.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:50966]
HTTP GET /static/admin/js/inlines.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/js/admin/RelatedObjectLookups.js 200 [0.00, 127.0.0.1:50966]
HTTP GET /static/admin/js/actions.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/js/prepopulate.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/js/urlify.js 200 [0.00, 127.0.0.1:50966]
HTTP GET /static/admin/js/prepopulate_init.js 200 [0.00, 127.0.0.1:50966]
HTTP GET /static/admin/js/vendor/xregexp/xregexp.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/js/theme.js 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/js/nav_sidebar.js 200 [0.00, 127.0.0.1:50966]
HTTP GET /static/admin/js/change_form.js 200 [0.00, 127.0.0.1:50966]
HTTP GET /static/admin/img/icon-addlink.svg 200 [0.00, 127.0.0.1:50965]
HTTP GET /static/admin/img/inline-delete.svg 200 [0.00, 127.0.0.1:50965]

It appears the tinymce.min.js file is not loaded, leading to a javascript error:
`ReferenceError: tinyMCE is not defined at HTMLDocument.<anonymous> (init tinymce.js:63:5)`

tinymce.js reference:
`  ready(function() {
    if (!tinyMCE) {
      throw 'tinyMCE is not loaded. If you customized TINYMCE_JS_URL, double-check its content.';
    }`

Have tried both overriding the TINYMCE_JS_URL in the setting.py file and using the default.

**Comment by claudep** [comment]
I just tested in one of my projects and the TinyMCE widget was loading fine. Something should be wrong in your setup. I'll close the ticket, but if you give us some sample code, maybe someone can continue to give you help.
