### ISSUE TITLE
django-tinymce==4.0.0: formatselect is not rendered in toolbar

### ISSUE THREAD

**Issue by urzbs** [jazzband/django-tinymce#470]
**Issue Description**

I am experiencing an issue with `django-tinymce==4.0.0` in my project. When using the default `TINYMCE_DEFAULT_CONFIG`, the `formatselect` option is not rendered in the toolbar.

**Configuration Details**

Here is the configuration being used:

```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'myapp',
]

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": False,
    "plugins": "advlist,autolink,lists,link,image,charmap,print,preview,anchor,"
               "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
               "code,help,wordcount",
    "toolbar": "undo redo | formatselect | "
               "bold italic backcolor | alignleft aligncenter "
               "alignright alignjustify | bullist numlist outdent indent | "
               "removeformat | help",
}
```

**Observed Behavior**

The `formatselect` option does not appear in the toolbar as expected:

![image](https://github.com/jazzband/django-tinymce/assets/41008226/e6e9f601-ddda-40e0-b356-34af6ca72bc8)

**Workaround**

When downgrading to `django-tinymce==3.7.1`, the `formatselect` option is rendered correctly:

![image](https://github.com/jazzband/django-tinymce/assets/41008226/e84dece2-3b76-4341-a1ef-f5ceb3d68cae)

**Reproduction Steps**

I have verified this behavior in a minimal Django application that only includes `django-tinymce`. The relevant parts of the application code are as follows:

*HTML Template:* (myapp/testing.html)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    {{ form.media }}
</head>
<body>
    {{ form }}
</body>
</html>
```

*View:*
```python
from django.views.generic import FormView
from myapp.forms import MyModelForm

class MyFormView(FormView):
    form_class = MyModelForm
    template_name = "myapp/testing.html"
```

*Model:*
```python
from django.db import models
from tinymce.models import HTMLField

class MyModel(models.Model):
    description = HTMLField()
```

*Form:*
```python
from django.forms import ModelForm
from myapp.models import MyModel

class MyModelForm(ModelForm):
    class Meta:
        model = MyModel
        fields = '__all__'
```

*Tested Browsers:*
* Chrome Version 125.0.6422.142 (latest as of issue creation-date)

**Request for Assistance**

Could you please investigate why the `formatselect` option is not rendered in the toolbar with `django-tinymce==4.0.0`? Any guidance or solutions to resolve this issue would be greatly appreciated.

Thank you for your assistance.

**Comment by claudep** [comment]
In version 4, we migrated from TinyMCE 5 to TinyMCE 6. Search for `formatselect` on https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/ and you will find your answer!

**Comment by urzbs** [comment]
Thank you for the quick help! 
replaced ``formatselect`` with ``blocks``
```
TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": False,
    "plugins": "advlist,autolink,lists,link,image,charmap,print,preview,anchor,"
               "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
               "code,help,wordcount",
    "toolbar": "undo redo | blocks | "
               "bold italic backcolor | alignleft aligncenter "
               "alignright alignjustify | bullist numlist outdent indent | "
               "removeformat | help",
}
```
---

The default for ``TINYMCE_DEFAULT_CONFIG`` (when not specified in settings.py) is the old schema
Also the documentation examples:
https://django-tinymce.readthedocs.io/en/latest/installation.html#configuration

**Comment by claudep** [comment]
Oh yes, absolutely, we need to fix that!

**Comment by claudep** [comment]
Would you like to check the pull request referenced above?

**Comment by urzbs** [comment]
The pull request looks good to me for this issue in particular.

However, I have also cross-checked the more extensive example with version `3.7.1` to test if there are any elements (in the toolbar) missing.

Yes, there are. Additionally, there is a mismatch between:

- **OLD:** `fontsizeselect`
- **NEW:** `fontsize`

- **OLD:** `fontselect`
- **NEW:** `fontfamily`

So, the updated configuration should be:

```python
TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",
    "width": "960px",
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "
               "fullscreen insertdatetime media table paste code help wordcount spellchecker",
    "toolbar": "undo redo | bold italic underline strikethrough | fontfamily fontsize blocks | alignleft "
               "aligncenter alignright alignjustify | outdent indent | numlist bullist checklist | forecolor "
               "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
               "fullscreen preview save print | insertfile image media pageembed template link anchor codesample | "
               "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "language": "es_ES",  # To force a specific language instead of the Django current language.
}
```

However, I have noticed that in both versions, you don't see any interactable changes in the toolbar for the following items:

- `checklist`
- `casechange`
- `permanentpen`
- `formatpainter`
- `emoticons`
- `save`
- `insertfile`
- `pageembed` (no effect, media submenu)
- `template`
- `codesample`
- `a11ycheck`
- `ltr`
- `rtl`
- `showcomments`
- `addcomment`

I'm not sure if these require any other special treatment to show up.

---

The menu bar seems fine, but I can't guarantee I didn't miss something 🤣

**Comment by claudep** [comment]
* `checklist`, `casechange`, `permanentpen`, `formatpainter`, `insertfile`, `pageembed`, `template`, `a11ycheck`, `showcomments`, `addcomment` are only available for paid TinyMCE subscriptions. I'll remove them from the docs.
 * `emoticons`, `save`, `codesample` are plugins and should be mentioned under the "plugins" key. `ltr` and `rtl` need the `directionality` plugin.

Thanks a lot for your review :heart:, I'll suggest a second patch for these updates.

**Comment by claudep** [comment]
Updates suggested in pr #472

**Comment by urzbs** [comment]
Thank you for addressing this issue so promptly and professionally. Your quick and efficient handling of the matter was truly extraordinary.

This experience has significantly increased my trust in the ``django-tinymce`` project, and I look forward to its ongoing support and development.

**Comment by claudep** [comment]
Thanks for your kind words!

**Comment by claudep** [comment]
I think we can consider now this as fixed. Thanks very much for the report.
