### ISSUE TITLE
Upgrade to TinyMCE 6.8.4

### ISSUE THREAD

**Issue by tjdett** [jazzband/django-tinymce#473]
TinyMCE 6.8.3 has security vulnerabilities that are now patched in TinyMCE 6.8.4.

As per [the release notes](https://www.tiny.cloud/docs/tinymce/6/6.8.4-release-notes/) there were only security bugfixes in 6.8.4, so it should be relatively simple to upgrade.

**Comment by claudep** [comment]
Thank you very much Tim for noticing us. A new version was just released with 6.8.4 (https://pypi.org/project/django-tinymce/)
