### ISSUE TITLE
Add a custom button in django-tinymce 4.1

### ISSUE THREAD

**Issue by yuriy65** [jazzband/django-tinymce#481]
Hello,

How can I add a custom button to the widget in django-tinymce 4.1? Unfortunately, the docs aren't very helpful.

I appreciate any help you can provide.

**Comment by MarcinWieczorek** [comment]
https://www.tiny.cloud/docs/tinymce/latest/custom-basic-toolbar-button/
You need to create a plugin and then add it to your settings `TINYMCE_DEFAULT_CONFIG` like you would add a normal plugin. Make sure to make `plugin.min.js` visible as a static file.
